### ISSUE TITLE
ModuleNotFoundError: No module named 'deep_sort_realtime'

### ISSUE THREAD

**Issue by prince0310** [Mazen-Elaraby/DeepSORT#1]
please upload deep_sort_realtime folder or else mention the step to use this repo

**Comment by Mazen-Elaraby** [comment]
Thank you for reminding me of this, I forgot to include the dependencies in my readme file, will be doing it soon.

**Comment by MuhammadShifa** [comment]
Hi @prince0310 , you can install it via pip package.
`pip install deep-sort-realtime`
